version: 0.2
phases:
  build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 561880438739.dkr.ecr.us-east-1.amazonaws.com
      - docker build -t authsplit .
      - docker tag authsplit:latest 561880438739.dkr.ecr.us-east-1.amazonaws.com/authsplit:latest
      - docker push 561880438739.dkr.ecr.us-east-1.amazonaws.com/authsplit:latest
      - count=$(aws ecs list-tasks --cluster NDS-CYNC-DEV-Selenium-Grid-Cluster --service test --query 'taskArns[*]' --output text | wc -l)
      - |
        if [ $count -eq 0 ]; then
          aws ecs run-task --cluster NDS-CYNC-DEV-Selenium-Grid-Cluster --task-definition test --overrides '{"containerOverrides":[{"name":"authsplit","command":["/bin/bash","-c","deploy.sh"]}]}'
        fi
      - aws ecs update-service --cluster NDS-CYNC-DEV-Selenium-Grid-Cluster --service test --desired-count 0
      - aws ecs run-task --cluster NDS-CYNC-DEV-Selenium-Grid-Cluster --task-definition authsplit --overrides '{"containerOverrides":[{"name":"authsplit", "entryPoint":["/bin/bash","-c","deploy.sh"]}]}'
      - aws ecs update-service --cluster NDS-CYNC-DEV-Selenium-Grid-Cluster --service test --desired-count $count